### ISSUE TITLE
SFS needs implementation

### ISSUE THREAD

**Issue by DLGesus** [ryan-jacobs1/oxidizedos#1]
Halogen, the tool to develop this Rust operating system contains a feature for constructing a Simple FileSystem(SFS) file but the operating system repository still does not support the SFS system. A filesystem is a necessary part for an operating system project and could be beneficial to other parts of the OS. If this is a needed feature, I'd be glad to help out and implement it.

**Comment by ryan-jacobs1** [comment]
This would be a useful feature. Feel free to open a PR if you implement it.
